version: '3.4'

networks:
  nginx-test:
    driver: bridge

services:

  &nginx nginx:
    image: klimby/nginx:latest
    container_name: nginx-test
    hostname: *nginx
    ports: ["8080:80"]
    volumes:
      - ./app:/app
      - ./test.conf:/etc/nginx/conf.d/test.conf:ro
    networks:
      - nginx-test



